n = input("Digite algo:")
print('Os caracteres {} são válidos?'.format(n), n.isidentifier())
print('{} É alfabético?'.format(n),n.isalpha())
print('{} É numérico?'.format(n), n.isnumeric())
print('{} É alfanumérico?'.format(n), n.isalnum())
print('{} É um caractere?'.format(n), n.isascii())
print('{} É decimal?'.format(n), n.isdecimal())
print('{} É um dígito?'.format(n), n.isdigit())
print('{} Está tudo minúsculo?'.format(n), n.islower())
print('{} É imprimível?'.format(n), n.isprintable())
print('{} Está espaçado?'.format(n), n.isspace())
print('{} É um título?'.format(n), n.istitle())
print('{} Está tudo maiúsculo?'.format(n), n.isupper())
print('O tipo primitivo de {} é:'.format(n), type(n))
